web-client/config/routes.rb
WebClient::Application.routes.draw do
  root :to => 'searches#show'

  resource :dashboards, :only => [:show], :path => 'dashboard'

  #footer
  
 # get 'about' => 'abouts#show', :as => 'about'

  resource :status, :only => [:index], :path => 'status'

  resource :omniauth, :only => [:google, :authenticate_google, :facebook, :authenticate_facebook] do
    get '/facebook' => 'omniauth#facebook', :as => 'login_facebook'
    get '/authenticate_facebook' => 'omniauth#authenticate_facebook', :as => 'authenticate_facebook'
    get '/add_facebook' => 'omniauth#add_facebook_account', :as => 'add_facebook'
    get '/google' => 'omniauth#google', :as => 'login_google'
    get '/add_google' => 'omniauth#add_google_account', :as => 'add_google'
    get '/authenticate_google' => 'omniauth#authenticate_google', :as => 'authenticate_google'
  end

  resource :googles, :only => [:upload_video, :upload_video_action] do
    get '/upload_video' => 'googles#upload_video', :as => 'upload_video'
    post '/upload_video' => 'googles#upload_video_action'
  end

  resource :facebooks, :only => [:status, :post_status, :upload_video, :upload_video_create] do
    get '/wall' => 'facebooks#wall', :as => 'wall'
    get '/status' => 'facebooks#status', :as => 'status'
    post '/status' => 'facebooks#post_status'
    get '/upload_photo' => 'facebooks#upload_photo', :as => 'upload_photo'
    post '/upload_photo' => 'facebooks#upload_photo_create'
    get '/upload_video' => 'facebooks#upload_video', :as => 'upload_video'
    post '/upload_video' => 'facebooks#upload_video_create'
  end

  resource :twitter, :only => [:status, :post_status] do
    get '/timeline' => 'twitter#timeline', :as => 'timeline'
    get '/status' => 'twitter#status', :as => 'status'
    post '/status' => 'twitter#post_status'
  end

  resources :jots do
    get 'thumbsup'
    get 'thumbsdown'
    get 'destroy'
    post 'comments' => 'jots#create_comments'
    get 'fav'
    get 'rejot'

    resources :jot_comments, :path => 'comments'
  end

  resource :profiles
  
  resource :account_settings, :except => [:update, :new, :create, :destroy, :edit, :show] do
    post '/update_email' => 'account_settings#update_email', :as => 'update_email'
    post '/update_password' => 'account_settings#update_password', :as => 'update_password'
    post '/update_privacy' => 'account_settings#update_privacy', :as => 'update_privacy'
    post '/update_your_stream' => 'account_settings#update_your_stream', :as => 'update_your_stream'
    post '/update_default_post' => 'account_settings#update_default_post', :as => 'update_default_post'
    post '/update_connection' => 'account_settings#update_connection', :as => 'update_connection'
    post '/update_media_upload' => 'account_settings#update_media_upload', :as => 'update_media_upload'
  end


  match '/auth/twitter/callback', :to => 'omniauth#authenticate_twitter'

  get 'contact' => 'contacts#index', :as => 'contact'
  get 'goodies' => 'goodies#index', :as => 'goodies'
  get 'api'     => 'apis#index', :as => 'api'
  get 'help'    => 'helps#index', :as => 'help'
  get 'terms'   => 'terms#index', :as=> 'terms'
  get 'privacy' => 'privacys#index', :as=> 'privacy'


  
  get 'member'        => 'welcomes#member', :as => 'member'
  
  get 'profile_other' => 'welcomes#profile_other', :as => 'profile_other'
  get 'search_people' =>  'welcomes#search_people', :as => 'search_people'
  get 'jot_detail_active' => 'welcomes#jot_detail_active', :as => 'jot_detail_active'

  get 'nest_manager'  => 'nests#index', :as => 'nest_manager'
  get 'inbox'         => 'welcomes#inbox', :as => 'inbox'

  get 'new-index' => 'welcomes#new_index'

  get '/forgot_password' => 'authentications#forgot_password', :as => 'forgot'
  post '/forgot_password' => 'authentications#notify_forgot_password'

  resources :authentications

  # registration
  get 'signup' => 'registrations#new', :as => :signup
  get 'logout' => 'authentications#logout', :as => :logout
  post 'signup' => 'registrations#create', :as => :signup_create

  resource :tests

  resources :maps

  resources :notification, :path => 'notification', :only => [:index, :destroy] do
    get 'destroy'
  end

  resources :files
  get 'about' => 'abouts#show'

  get 'home_detail' => 'homes#show'
  get 'hot_stuff'     => 'hotstuffs#show'
  get 'jotpost' => 'jotposts#show'

  resource :searches, :path => 'search' do
    get '/get_tag' => 'searches#get_tag'
    get '/get_user' => 'searches#get_user'
  end

end

web-client/app/views/template/_main_about.html.erb
<script  id="main-about-template" type="text/template">
 <div class="main_content about_content">
<div class="about_tab_header">
              <ul>
                <li class="about_head_left"><a href="" class="about_active about_default">About</a></li>
                <li class="about_head_middle"><a href="" class="what_jotky_default">What Jotky Can DO For You?</a></li>
                <li class="about_head_right"><a href="" class="faq_default">FAQ</a></li>
              </ul>
            </div>
            <div id="aboutJotky" class="about_jotky">
              <div class="about_tab_body">
                <div class="about_tab_body_top">
                  <span class="about_jotky_tittle">About Jotky</span>
                  <span class="about_jotky_icon"></span>
                  <div class="clear"></div>
                </div>
                <div class="about_tab_body_middle">
                  <p class="first_paragraph">
                    Jotky is a crowd contributed social network platform that allows you to share interesting topic.
                    Choose what topic to follow and its content filtering and cloud tag system will find you relevant topic only.
                  </p>
                  <p class="second_paragraph">
                    Users contribution called Jots. It can be news, share links or whatever they have in mind.
                    Complete your Jots by defining them with tags and attaching links or media.
                    Published Jots are added to stream and you can go to the main page to view and filter it based on your preference.
                    Notes and users are geo-located. News stream will be displayed in real time and post notes can be shared via integrated websites.
                    Users can also chat in its forum, share, download, upload files, videos, audio, pictures, as well as producing relevant search results that is most important to them.
                  </p>
                  <p class="third_paragraph">
                    Users contribution called Jots. It can be news, share links or whatever they have in mind.
                    Complete your Jots by defining them with tags and attaching links or media. Published Jots are added to stream and you can go to the main page to view and filter it based on your preference.
                    Notes and users are geo-located. News stream will be displayed in real time and post notes can be shared via integrated websites.
                    Users can also chat in its forum, share, download, upload files, videos, audio, pictures, as well as producing relevant search results that is most important to them.
                  </p>
                </div>
                <div class="clear"></div>
              </div>
              <div class="about_tab_body_bottom">
                <ul>
                  <li><a href="" class="what_jotky_bottom_link">What jotky can do for you</a></li>
                  <li><a href="" class="faq_bottom_link">FAQ</a></li>
                </ul>
              </div>
            </div>


     <!-- WHAT JOTKY CAN DO FOR YOU -->

          <div id="whatJotky" class="what_jotky">
            <div class="what_jotky_tittle">What Jotky Can Do For You</div>
            <div class="about_jotky_body">
              <div class="what_jotky_icon">&nbsp;</div>
              <div class="what_jotky_text">
                <p class="no_margin_top">
                  Jotky is a versatile way to connect with friends, share photos, music, videos, thoughts, news, documents, search for,
                  upload and download and anything at all you'd like to share with your world.
                </p>
                <p>
                  Whether it's to share pictures or videos, connect with long long lost school mates,
                  updating your status (Jotky lets users updates statuses on all integrated social networking platforms),
                  letting friends know where you are, loking for a telephone number for the nearest pizza parlor to just
                  Jotting down what you have in mind. Every aspect of a social networking platform and more is made accessible through Jotky.
                </p>
                <p>
                  Forum 2.0 function will also allow users to post, view and sell items,
                  define them with tags for other users to search for, basing results on keywords and geographical locatios.
                  Making Jotky's forum efficient for buying and selling. As well as its basic forum 2.0 functions.
                </p>
                <p>
                  Homepage is a great place to go to find out what we're up to, as well as how to use the site.
                  You can also <a href="">watch Jotky tutorial video</a> series to learn how to use our basic features.
                </p>
              </div>
              <div class="clear"></div>
            </div>
            <div class="about_tab_body_bottom">
              <ul>
                <li><a href="" class="about_bottom_link">About</a></li>
                <li><a href="" class="faq_bottom_link">FAQ</a></li>
              </ul>
            </div>
            <div class="clear"></div>
          </div>

          <!-- END OF WHAT JOTKY CAN DO FOR YOU -->



            <div class="clear"></div>
          </div>

</script>

web-client/app/views/template/_main_forgot.html.erb
<script  type="text/template" id="main-forgot-template">
 <div class="forgotPwd_content main_content">
    <div class="opening_text">
      <p class="line_one">Identify Your Account</p>
    </div>
    <%= form_tag forgot_path, :id => 'main-forgot-form' do -%>
      <table class="box_forgot">
        <tbody>
          <tr class="reg_email">
            <td class="label_registration">
              <%= label_tag 'forgot_email', 'E-mail' %>
              <%= text_field_tag 'forgot[email]' %>
            </td>
            <td class="alert_registration main-forgot-form-field-alert">
              <p class="default_text">
                <%= label_tag 'forgot_email', 'your email address, please' %>
              </p>
              <p class="error hidden"></p>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="login_button bottom_registrationPath" id="forgot">
          <%= submit_tag 'Recovery' %>
        </div>
    <% end %>
    <div class="clear"></div>
  </div>
</script>

web-client/app/views/template/_main_listing_jot_jotbar.html.erb
<script type="text/template" id="main-listing-jot-jot-bar">

</script>
<div class="side-left">
  <ul>
    <li class="leftMenu_searchResult">
      <a href="" onmouseout="heal()" class="side-menu-top-left">
        <label>Jots&nbsp;</label>
        <span class="jots-icon">&nbsp;</span>
      </a>
      <span class="triangle" style="display:none" onmouseout="heal()">&nbsp;</span>
    </li>
    <li class="leftMenu_searchResult">
      <a href="" onmouseout="heal()" >
        <label>People&nbsp;</label>
        <span class="people-icon">&nbsp;</span>
      </a>
      <span class="triangle" style="display:none" onmouseout="heal()">&nbsp;</span>
    </li>
    <li class="leftMenu_searchResult">
      <a href="" onmouseout="heal()" >
        <label>Media&nbsp;</label>
        <span class="media-icon">&nbsp;</span>
      </a>
      <span class="triangle" style="display:none" onmouseout="heal()">&nbsp;</span>
    </li>
    <li class="leftMenu_searchResult">
      <a href="" onmouseout="heal()" class="side-menu-bottom-left">
        <label>Places&nbsp;</label>
        <span class="places-icon">&nbsp;</span>
      </a>
      <span class="triangle" style="display:none" onmouseout="heal()">&nbsp;</span>
    </li>
  </ul>
</div>

web-client/app/views/template/_main_magicbox_jot_input.html.erb
<script type="text/template" id="main-magicbox-jot-input-template">

  <%= form_tag jots_path(:format => :json), :id => 'main-magicbox-jot-input-form', :class => 'main-magicbox-jot-input-form' do %>
    <div class="jot_search search jot-tab-content clearfix">
      <%= text_field_tag 'jot[title]', nil, :placeholder => 'Tags, places, users, search from them here!', :id => 'jot-input-title' %>
      <%= submit_tag "" %>
    </div>

    <div class="jot_buttons_path jot-tab-content">
      <div class="left">
        <ul>
          <li>
            <a href="#" class="write_more_but jot_buttons_color jot-bar-button" id="jot-bar-write-more">
              <span class="jot_write_icon">&nbsp;</span>
              <span class="jot_button_text">Write more</span>
            </a>
          </li>
          <li>
            <a href="#" class="clip_but jot_but jot_buttons_color jot-bar-button" id="jot-bar-clip">
              <span class="jot_clip_icon">&nbsp;</span>
              <span class="jot_button_text">Clip</span>
            </a>
          </li>
          <li>
            <a href="#" class="jot_but loc_but jot_buttons_color jot-bar-button" id="jot-bar-location">
              <span class="jot_location_icon">&nbsp;</span>
              <span class="jot_button_text">Location</span>
            </a>
          </li>
          <li>
            <a href="#" class="jot_but tags_but jot_buttons_color jot-bar-button" id="jot-bar-tag">
              <span class="jot_tags_icon">&nbsp;</span>
              <span class="jot_button_text">Tags</span>
            </a>
          </li>
          <li>
            <a href="#" class="jot_buttons_color jot_facebook jot-bar-button" id="jot-bar-facebook">
              <span class="jot_fb_icon">&nbsp;</span>
            </a>
          </li>
          <li>
            <a href="#" class="jot_buttons_color no_margin_right jot-bar-button" id="jot-bar-twitter">
              <span class="jot_twitter_icon">&nbsp;</span>
            </a>
          </li>
        </ul>
      </div>
      <div class="jot_button_right">
        <span class="jot_count" id="jot-input-text-length">140</span>
        <a href="" class="jot_down_arrow">&nbsp;</a>
      </div>
    </div>
   
    <div class="jot_mode_hide" id="jot-input-more">

      <input type="submit" class="jot_green_bg" value="Jot" />
      <div class="clear"></div>
    </div>
  <% end %>
</script>

web-client/app/views/template/_main_magicbox_jot_input_location.html.erb
<script type="text/template" id="main-magicbox-jot-input-location-template">
  <div class="jot_add_location clearfix">

    <div class="add_location_top">
      <span class="add_location_media">&nbsp;</span>
      <span class="add_more_text">Add location</span>
      <a href="" class="attach_more_location">Attach more location</a>
    </div>
    <div class="up_media_top">
      <div class="upload_media_bottom">
        <div class="clearfix">
          <div class="left"> 
            <%= text_field_tag 'jot[location]', nil, :class => "add_own_location no-float", :id => "field-to-location", :autocomplete => :off %>
          </div>
          <div class="right">
            <p class="add_location_info">type an area or use google maps coordinate to add location to your jot</p>
          </div>
        </div>
      </div>

    </div>

    <div id="jot-input-location-list">
      
    </div>

    <!-- div class="up_media_loc">
      <div class="loc_style own_jot">
        <a class="own_location" href=""><img alt="" src="assets/own-location.png"></a>
        <span class="location_info">
          <a class="tittle_location" href="">Party's Groove</a>
          <input type="text" class="no_margin_left image_upload_input" style="display: none;">
          <span class="road_location">Jl. Warung Buncit 09A,</span>
          <span class="no_padding_top country_location">Jakarta Selatan, Indonesia</span>
        </span>
        <a class="close_img_path" href="" style="">x</a>
      </div>

      <div class="loc_style own_jot">
        <a class="own_location" href=""><img alt="" src="assets/own-location.png"></a>
        <span class="location_info">
          <a class="tittle_location" href="">Party's Groove</a>
          <input type="text" class="no_margin_left image_upload_input" style="display: none;">
          <span class="road_location">Jl. Warung Buncit 09A,</span>
          <span class="no_padding_top country_location">Jakarta Selatan, Indonesia</span>
        </span>
        <a class="close_img_path" href="" style="">x</a>
      </div>
    </div -->

  </div>
</script>

web-client/app/views/template/_main_magicbox_jot_input_tag.html.erb
<script type="text/template" id="main-magicbox-jot-input-tag-template">
  <div class="jot_tags_post clearfix">
    <%= form_tag jots_path, :id => '#main-magicbox-jot-input-tag-form', :class => 'main-magicbox-jot-tag-form' do %>
    <div class="jot_top_tags">
      <span class="top_tags_style jot_tags_icon">&nbsp;</span>
      <span class="top_tags_text">Tags of this post</span>
    </div>
    <div class="jot_middle_tags">
      <ul>
        <li class="Lev_1">
          <span class="active_choiceTexts choice_text">MusicVid</span>
          <span class="jot_middle_tags_active"></span>
        </li>
        <li class="Lev_1">
          <span class="active_choiceTexts choice_text">8Bit</span>
          <span class="jot_middle_tags_active"></span>
        </li>
        <li class="Lev_1 no_padding_right">
          <span class="active_choiceTexts choice_text">Cartoon</span>
          <span class="jot_middle_tags_active"></span>
        </li>
      </ul>
      <div class="clear"></div>
    </div>
    <div class="jot_bottom_tags"></div>
    <% end %>
  </div>
</script>

web-client/app/views/template/_main_magicbox_login.html.erb
<script type="text/template" id="main-magicbox-login-template">
  <div class="login_content clearfix">
    <div class="left">
      <div class="left">
        <div class="box_signin">
          <h2>Login to start experience jotky</h2>
          <%= form_tag authentications_path, :id => "main-magicbox-login-form" do %>
            <div class="form_login">
              <div class="username">
                <%= label_tag 'authentication_username', 'Username' %>
                <%= text_field_tag 'authentication[username]' %>
                <div class="clear"></div>
              </div>
              <div class="password">
                <%= label_tag 'authentication_password', 'Password' %>
                <%= password_field_tag 'authentication[password]' %>
                <div class="clear"></div>
              </div>
              <div class="remember_login">
                <div class="left">
                  <%= check_box_tag :remember_me%>
                  <p class="checkbox">Remember me on this computer</p>
                </div>
                <div class="right">
                  <a href="javascript:void(0)" class="forgot_password link-forgot-password">forgot password?</a>
                </div>
                <div class="clear"></div>
              </div>
              <div class="login_button">
                <%= submit_tag 'Login' %>
                <div class="clear"></div>
              </div>
              <div class="clear"></div>
            </div>
          <% end %>
        </div>
        <div class="box_signinBottom">
          <div class="login_with">
            <p>or login with?</p>
            <a href="#" class="FB"></a>
            <a href="#" class="twitter"></a>
          </div>
        </div>
      </div>
      <div class="login_separator">
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
    </div>
    <div class="right">
      <div class="login_path">
        <span class="text">create a Jotky account</span>
        <a href="javascript:void(0);" class="signup_button link-to-registration">Sign Up</a>
        <span class="discover">and discover everything!</span>
      </div>
      <div class="clear"></div>
    </div>
    <div class="clear"></div>
  </div>
</script>

web-client/app/views/template/_main_magicbox_navigation.html.erb
<script id="main-magicbox-navigation-template" type="text/template">
  <div class="top_button" id="main-magicbox-navigation">
    <a href="#" class="search_icon main-magicbox-navigation-search-link">
      <span class="img_1 main-magicbox-navigation-link-icon-1"></span>
      <span class="search_text main-magicbox-navigation-link-text">Search</span>
      <span class="img_2 main-magicbox-navigation-link-icon-2"></span>
    </a>
    <a href="#" class="jot_icon main-magicbox-navigation-jot-link">
      <span class="img_1 main-magicbox-navigation-link-icon-1"></span>
      <span class="jot_text main-magicbox-navigation-link-text">Jot</span>
      <span class="img_2 main-magicbox-navigation-link-icon-2"></span>
    </a>
    <a href="#" class="sign_up main-magicbox-navigation-login-link">
      Sign up or Login
    </a>
    <div class="clear"></div>
  </div>
</script>

web-client/app/views/template/_main_magicbox_navigation_private.html.erb
<script id="main-magicbox-navigation-private-template" type="text/template">
  <div class="top_button" id="main-magicbox-navigation-private">
    <div class="left">
      <a class="search_icon main-magicbox-navigation-search-link" href="#" id="main-magicbox-navigation">
        <span class="img_1 main-magicbox-navigation-link-icon-1"></span>
        <span class="search_text main-magicbox-navigation-link-text">Search</span>
        <span class="img_2 main-magicbox-navigation-link-icon-2"></span>
      </a>
      <a class="jot_icon main-magicbox-navigation-jot-link" href="#">
        <span class="img_1 main-magicbox-navigation-link-icon-1"></span>
        <span class="jot_text main-magicbox-navigation-link-text">Jot</span>
        <span class="img_2 main-magicbox-navigation-link-icon-2"></span>
      </a>
    </div>
    <div class="right">
      <a class="new_update_notactive r-notification-tab" href="#" id="r-notification-tab">
        <span class="update_icon"></span>
        <span class="update_text">24 New Updates</span>
      </a>
      <a id="user_logged" class="sign_up" href="#">
        <img alt="" src="/assets/little-avatar.png">
        <span class="nickname_logged"><%= @current_user['username'] %></span>
        <span class="user_little_badge">0</span>
      </a>
    </div>
    <div class="clear"></div>
  </div>
</script>

web-client/app/views/template/_main_magicbox_profile.html.erb
<script id="main-magicbox-profile-template" type="text/template">


</script>

web-client/app/views/template/_main_magicbox_profile_bio.html.erb
<script id="main-magicbox-profile-bio" type="text/template">
<div class="bio">
        <div class="bio_tag">
            <span>Bio</span>
            <% if @current_user['bio'].present? %>
              <a id="bioContent" href="#bioContent" class="empty_bio_text"><%=  @current_user['bio'] %></a>
            <% else %>
              <a id="bioContent" href="#bioContent" class="empty_bio_text">click to edit your bio</a>
            <% end %>

        </div>

    <div  id="profile-bio-edit">
<span>Bio</span>
  <%= form_tag profiles_path(:format => :json), :method => :put, :multipart => true, :id => 'form-current-bio', :class => 'empty_bio_field form-current form-current-2' do %>
    <div class="form-current-field">
      <%= text_area_tag :bio, @current_user['bio'], :name => "user[bio]", :class => 'field-text auto-resize', :placeholder => "write your short bio here. max 512 characters" %>
    </div>

    <div class="form-current-field form-current-field-right">
      <%= image_tag 'ajax-loader-2.gif', :id => 'form-current-bio-loader', :class => 'hidden' %>
      <%= submit_tag 'Save', :value => 'Save', :class => 'but_save_popup' %>
    </div>
  <% end %>
            
    </div>
  
</script>

web-client/app/views/template/_main_magicbox_profiling.html.erb
<script id="main-magicbox-profiling" type="text/template">
  <%= form_tag profiles_path(:format => :json), :method => :put, :multipart => true, :id => 'form-current-bio', :class => 'form-current form-current-2' do %>
    <div class="form-current-field">
      <%= text_area_tag :bio, @current_user['bio'], :name => "user[bio]", :class => 'field-text auto-resize', :placeholder => "write your short bio here. max 512 characters" %>
    </div>

    <div class="form-current-field form-current-field-right">
      <%= image_tag 'ajax-loader-2.gif', :id => 'form-current-bio-loader', :class => 'hidden' %>
      <%= submit_tag 'Save', :value => 'Save', :class => 'button-2' %>
    </div>
  <% end %>


   <%= form_tag profiles_path(:format => :json), :method => :put, :multipart => true, :id => 'form-current-location', :class => 'form-current' do |f|  %>
    <div class="form-current-field">
      <%= text_field_tag :location, @current_user['location'], :name => "user[location]", :class => 'field-text', :id => "field_to_location", :autocomplete => :off %>
      <%= hidden_field_tag :latitude, @current_user['latitude'], :name => "user[latitude]", :id => 'field_latitude' %>
      <%= hidden_field_tag :longitude, @current_user['longitude'], :name => "user[longitude]", :id => 'field_longitude' %>
    </div>

    <div class="form-current-field form-current-field-right">
      <%= image_tag 'ajax-loader-2.gif', :id => 'form-current-location-loader', :class => 'hidden' %>
      <%= submit_tag 'Save', :value => 'Save', :class => 'button-2' %>
    </div>
  <% end %>

</script>

web-client/app/views/template/_main_welcome.html.erb
<script id="main-welcome-template" type="text/template">
    <div class="welcome_content middle_content">
    <div class="welcome">
      <p>Welcome to</p>
    </div>
    <div class="big_logo"></div>
    <div class="main-text">
      <p>
        Lorem Ipsum is simply dummy text of the printing and typesetting industry.
        Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
        when an unknown printer took a galley of type and scrambled it to make a type specimen book.
        It has survived not only five centuries, but also the leap into electronic typesetting,
        remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets
      </p>
      <span></span>
      <div class="clear"></div>
    </div>
    <div class="green_button">
      <input type="submit" value="see our hottest contents" />
    </div>
    <div class="clear"></div>
    </div>
</script>